#!/bin/bash
if [ "$1" = "dance" ]; then
	touch ~/.dancekbenabled
	SPECIAL=true
else
	rm -f ~/.dancekbenabled
fi

if [ "$1" = "git" ]; then
	touch ~/.gitkbenabled
	SPECIAL=true
else
	rm -f ~/.gitkbenabled
fi

if [ -z "$SPECIAL" ]; then
	kbcolor "$1"
fi
